include: package:very_good_analysis/analysis_options.5.1.0.yaml

rules:
  avoid_equals_and_hash_code_on_mutable_classes: false
  constant_identifier_names: false
  lines_longer_than_80_chars: false
  public_member_api_docs: false
  use_setters_to_change_properties: false

analyzer:
  errors:
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    constant_identifier_names: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
    use_setters_to_change_properties: ignore
